<ELabel@MDLabel>:
    theme_font_size:"Custom"
    theme_font_name:"Custom"


<Recording>:
    data:{}
    size_hint_x:None
    orientation:'vertical'
    padding: dp(10)
    canvas:
        Color:
            rgba:[0,0,0,0]
            group:"color"
        RoundedRectangle:
            size:self.size
            pos:self.pos
            radius:root.radius
        RoundedRectangle:
            size:self.size
            pos:self.pos
            radius:root.radius
            group:"img"
        RoundedRectangle:
            size:self.size
            pos:self.pos
            radius:root.radius
            source:app.get_file("assets/shadow-black.png")

    Widget:

    ELabel:
        id:rtext
        markup:True
        text:""
        adaptive_height:True
        text_color:app.white_color

<MoodSection>:
    max_entries:10
    size_hint_y:None
    height:dp(200)
    mood:""
    orientation:'vertical'
    data:{}
    
    ELabel:
        text:root.mood
        font_name:app.bold_font
        font_size:"20sp"
        theme_text_color:"Custom"
        text_color:app.theme_cls.primaryColor
        adaptive_height:True

    MDRecycleView:
        data:root.data
        key_viewclass: 'viewclass'
        do_scroll_y: False
        do_scroll_x:True
        bar_color:0,0,0,0
        bar_inactive_color:self.bar_color
        effect_cls: "ScrollEffect"
        RecycleBoxLayout:
            default_size_hint: None, 1
            default_size: self.height, 1
            spacing:dp(10)
            size_hint_x:None
            width:self.minimum_width


<MusicProgress>:
    canvas:
        Color:
            rgba:app.theme_cls.onSecondaryContainerColor
        Line: 
            group:"line"
            cap:"round"
            joint:"round"
            width:1.3
        Color:
            rgba:app.theme_cls.onSecondaryContainerColor
        RoundedRectangle:
            size:[dp(5), dp(20)]
            radius:[dp(2.5)] * 4
            group:"handle"
            pos:[0, self.height/2]
        Color:
            rgba:app.theme_cls.inverseSurfaceColor[:-1] + [0.5]
        Line: 
            group:"_line"
            cap:"round"
            joint:"round"
            width:1.3

MDScreen:
    name:"recordings"

    MDLoadingIndicator:
        id:indicator
        shape_size:dp(100)
    
    MDScrollView:
        
        do_scroll_y:True
        do_scroll_x:False

        BoxLayout:
            id:container
            orientation:'vertical'
            size_hint_y:None
            padding: [dp(10), dp(10)]
            height:self.minimum_height
            spacing:dp(15)
            
            ELabel:
                text:"EarthFM"
                font_size:"45sp"
                font_name:app.main_font
                theme_text_color:"Custom"
                text_color:app.theme_cls.primaryColor
                padding:[0, 0, 0, dp(15)]
                adaptive_height:True

    MDBoxLayout:
        id:small_player
        size_hint_x:0.8
        size_hint_y:None
        height:dp(70)
        radius:dp(20)
        pos_hint:{"center_x":0.5}
        y:-self.height - dp(10)
        md_bg_color:app.theme_cls.surfaceContainerHighestColor
        MusicProgress:
            id:pg_bar




