<ELabel>:
    theme_font_size:"Custom"
    theme_font_name:"Custom"


<Recording>:
    data:{}
    size_hint_x:None
    orientation:'vertical'
    padding: dp(10)
    on_release:app.currently_playing = self.data
    canvas:
        Color:
            rgba:[0,0,0,0]
            group:"color"
        RoundedRectangle:
            size:self.size
            pos:self.pos
            radius:root.radius
        RoundedRectangle:
            size:self.size
            pos:self.pos
            radius:root.radius
            group:"img"
        RoundedRectangle:
            size:self.size
            pos:self.pos
            radius:root.radius
            source:app.get_file("assets/shadow-black.png")

    Widget:

    ELabel:
        id:rtext
        markup:True
        text:""
        adaptive_height:True
        text_color:app.white_color

<RoundedImage>:
    canvas:
        Color:
            rgba:[1,1,1,1]
        
        SmoothRoundedRectangle:
            pos: root.pos
            size: root.size
            radius:root.radius

        SmoothRoundedRectangle:
            pos: root.pos
            size: root.size
            radius:root.radius
            source:root.source

<MarqueeLabel>:
    size_hint:[1, 1]
    overlay_color:app.theme_cls.surfaceContainerHighestColor

    canvas.before:
        StencilPush
        Rectangle:
            pos: self.pos
            size: self.size 
        StencilUse
    canvas.after:
        StencilUnUse
        Rectangle:
            pos: self.pos
            size: root.size 
        StencilPop

    ELabel:
        text:" "
        id:label
        adaptive_width:True
        font_name:app.bold_font
        y:root.y + (root.height-self.height)/2
        on_width: root.on_label_width()

    GradientOverlay:
        id:overlay
        fade_width:dp(20)
        size_hint:[1,1]
        x:root.x + (root.width-self.width)/2
        y:root.y + (root.height-self.height)/2

<MoodSection>:
    max_entries:10
    size_hint_y:None
    height:dp(200)
    mood:""
    orientation:'vertical'
    data:{}
    
    ELabel:
        text:root.mood
        font_name:app.bold_font
        font_size:"25sp"
        theme_text_color:"Custom"
        text_color:app.theme_cls.primaryColor
        adaptive_height:True

    MDRecycleView:
        data:root.data
        key_viewclass: 'viewclass'
        do_scroll_y: False
        do_scroll_x:True
        bar_color:0,0,0,0
        bar_inactive_color:self.bar_color
        effect_cls: "ScrollEffect"
        RecycleBoxLayout:
            default_size_hint: None, 1
            default_size: self.height, 1
            spacing:dp(10)
            size_hint_x:None
            width:self.minimum_width

MDScreen:
    name:"recordings"
    on_enter:app.set_window_color(self.theme_cls.surfaceContainerColor)

    MDLoadingIndicator:
        id:indicator
        shape_size:dp(100)
    
    MDScrollView:
        
        do_scroll_y:True
        do_scroll_x:False

        BoxLayout:
            id:container
            orientation:'vertical'
            size_hint_y:None
            padding: [dp(10), dp(10)]
            height:self.minimum_height
            spacing:dp(20)
            
            BoxLayout:
                size_hint_y:None
                height:self.minimum_height

                ELabel:
                    text:"EarthFM"
                    font_size:"45sp"
                    font_name:app.main_font
                    theme_text_color:"Custom"
                    text_color:app.theme_cls.primaryColor
                    padding:[0, 0, 0, dp(15)]
                    adaptive_height:True
                
                BoxLayout:
                    size_hint_x:None
                    width:dp(70)
                    padding: [dp(20), 0, 0, dp(30)]
                    MDIconButton:
                        icon:"cog"
                        style:"tonal"
                        size_hint:[None, None]
                        size:[dp(40)] * 2
                        on_release:app.theme_cls.theme_style = "Dark" if app.theme_cls.theme_style == "Light" else "Light"


    BottomPlayer:
        id:btm_player
        pos_hint:{"center_x":0.5}
        y:-self.height-dp(10)
        size_hint_y:None
        height:dp(80)
        spacing: dp(15)
        padding: [dp(10), dp(10), dp(10), 0]
        orientation:'vertical'

        on_release:self.expand(lambda : app.screen_manager.switch_to(app.PlayerUI))

        canvas:
            Color:
                rgba:app.theme_cls.surfaceContainerHighestColor
            RoundedRectangle:
                group:"bg_rect"
                size:self.size
                pos:self.pos
                radius:btm_player.radius
        
        BoxLayout:
            spacing:dp(10)
            
            RoundedImage:
                id:p_img
                size_hint_x:None
                width:self.height
                radius:[dp(10)]*4

            BoxLayout:
                orientation: 'vertical'
                
                MarqueeLabel:
                    id:t_text

                ELabel:
                    id:a_text
                    text:" "
                    font_name:app.regular_font
                    font_size:"14sp"
                    adaptive_height:True

            MDIconButton:
                id:play_btn
                icon: "play"
                style: "filled"
                on_release:app.pause_play_icon(self)

        MDLinearProgressIndicator:
            id:pg_indicator
            size_hint_y:None
            height:dp(5)
            track_color:app.theme_cls.secondaryContainerColor
